language: php

php:
   # - '5.6'
   - '7.0'
   # - '7.1'

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - google-chrome-stable
      - xvfb

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
  - cp .env.ci .env
  - composer install --dev --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpmd app text codesize design naming unusedcode
  - php artisan dusk
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - gtaylor@electricwerks.com
    on_success: always
    on_failure: always
