language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'

sudo: false

before_script:
  - cp .env.travis .env
  #- mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate

script:
  - vendor/bin/phpmd app text cleancode codesize design naming unusedcode
  - vendor/bin/phpunit

notifications:
  email:
    recipients:
      - gtaylor@electricwerks.com
    on_success: always
    on_failure: always
